In [2]:
import numpy as np
arr  = np.array([[100 ,101 ,102, 103],[110 ,111, 112, 113],[120 ,121, 122, 123],[130 ,131, 132, 133]])


In [8]:
print(arr[1:3,[1,2,3]])

[[111 112 113]
 [121 122 123]]


In [9]:
import pandas as pd
df  = pd.DataFrame({'x':['a','a','b','b'],'y':['a','b','a','b'],'z':[10,50,20,60]})

In [11]:
df.groupby("y").sum()

z
y     
a   30
b  110

In [15]:
a = np.array([[[1, 2, 3], [4, 5, 6]],[[1,2,3],[4,5,6]]])
b = np.array([[10],[100]])
a * b

array([[[ 10,  20,  30],
        [400, 500, 600]],

       [[ 10,  20,  30],
        [400, 500, 600]]])

In [12]:
print(a)

[[1 2 3]
 [4 5 6]]


In [13]:
print(b)

[[ 10]
 [100]]


In [16]:
from nltk import ngrams

a = int('001000100011',2)
ans = ngrams(a.split(),4)

print(ans)

AttributeError: 'int' object has no attribute 'split'

In [17]:
def _print():
    print(10 + 5)

In [18]:
type(_print())

15


NoneType