In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#Pre processing training data set beer_training.txt
read_file = pd.read_csv (r'./beer_training.txt',delimiter='\t', header = None)
read_file.columns = ['calorific_value', 'nitrogen', 'turbidity', 'style', 'alcohol', 'sugars', 'bitterness', 'beer_id', 'colour', 'degree_of_fermentation']
read_file.to_csv (r'./beer_training.csv', index=None)
ts = pd.read_csv("./beer_training.csv",sep=",")
ts = ts.drop("beer_id", axis=1)
first_col = ts.pop("style")
ts.insert(8, "style", first_col)
ts.to_csv('./beer_training.csv', index=None)
ts.head()
#df.tail()

calorific_value  nitrogen  turbidity   alcohol  sugars  bitterness  colour  \
0        45.305310  0.459548   1.917273  4.227692   16.67   12.568947   11.04   
1        43.889381  0.548977   3.186364  4.289231   16.73   14.974000   13.44   
2        41.588496  0.542847   1.568182  4.344615   16.48   11.848789   14.04   
3        44.553097  0.480301   1.871818  4.424615   18.59   13.879632   12.48   
4        41.013274  0.441860   2.345455  4.264615   16.35   12.186053   12.12   

   degree_of_fermentation style  
0               62.178571   ale  
1               63.032857   ale  
2               63.468571   ale  
3               63.531429   ale  
4               63.747143   ale

In [3]:
#Pre processing test data set beer_test.txt
read_file = pd.read_csv (r'./beer_text.txt',delimiter='\t', header = None)
read_file.columns = ['calorific_value', 'nitrogen', 'turbidity', 'style', 'alcohol', 'sugars', 'bitterness', 'beer_id', 'colour', 'degree_of_fermentation']
read_file.to_csv (r'./beer_text.csv', index=None)
testSet = pd.read_csv("./beer_text.csv",sep=",")
testSet = testSet.drop("beer_id", axis=1)
first_col = testSet.pop("style")
testSet.insert(8, "style", first_col)
testSet.to_csv('beer_text.csv', index=None)
testSet.head()
#df.tail()

calorific_value  nitrogen  turbidity   alcohol  sugars  bitterness  colour  \
0        41.721239  0.503276   2.628182  4.015385   16.73   10.452789   13.44   
1        42.429204  0.525512   1.776364  4.092308   16.72   10.999526   12.24   
2        45.880531  0.443233   2.628182  4.276923   16.68   13.456368   10.92   
3        45.305310  0.471668   1.806364  4.126154   18.84    9.202737   10.92   
4        38.977876  0.392846   2.272727  4.015385   16.77    9.457895   10.56   

   degree_of_fermentation style  
0               55.337143   ale  
1               58.380000   ale  
2               58.382857   ale  
3               58.525714   ale  
4               58.900000   ale

In [4]:
#X = ts.iloc[:,:-1].values
#y = ts.iloc[:,8].values

In [30]:
# Test and Training set
X_train = ts.iloc[:,[0,1,2,3,4,5,6,7]].values
y_train = ts.iloc[:, 8].values

X_test = testSet.iloc[:,[0,1,2,3,4,5,6,7]].values
y_test = testSet.iloc[:, 8].values
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(124, 8)
(124,)
(30, 8)
(30,)


In [31]:
#Feature Scale
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [32]:
#kNN
from sklearn.svm import SVC
classifier = SVC()
classifier.fit(X_train, y_train)

SVC()

In [33]:
#Prediction
y_pred = classifier.predict(X_test)

In [34]:
#Confusion Matrix
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
clsfnReport = classification_report(y_test, y_pred)
confReport = confusion_matrix(y_test, y_pred)
acc = accuracy_score(y_test, y_pred)
print(clsfnReport)
print(confReport)
print(acc)

              precision    recall  f1-score   support

         ale       1.00      0.80      0.89        10
       lager       0.83      1.00      0.91        10
       stout       1.00      1.00      1.00        10

    accuracy                           0.93        30
   macro avg       0.94      0.93      0.93        30
weighted avg       0.94      0.93      0.93        30

[[ 8  2  0]
 [ 0 10  0]
 [ 0  0 10]]
0.9333333333333333


In [25]:
y_pred_train = classifier.predict(X_train)
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
clsfnReport = classification_report(y_train, y_pred_train)
confReport = confusion_matrix(y_train, y_pred_train)
acc = accuracy_score(y_train, y_pred_train)
print('Classification Report')
print(clsfnReport)
print('Confusion Matrix')
print(confReport)
print('Accuracy')
print(acc)

Classification Report
              precision    recall  f1-score   support

         ale       0.93      0.98      0.95        42
       lager       0.98      0.91      0.94        44
       stout       0.95      0.97      0.96        38

    accuracy                           0.95       124
   macro avg       0.95      0.95      0.95       124
weighted avg       0.95      0.95      0.95       124

Confusion Matrix
[[41  0  1]
 [ 3 40  1]
 [ 0  1 37]]
Accuracy
0.9516129032258065
